<a href="https://colab.research.google.com/github/comsadavid/AI-solutions/blob/main/competitions/mlcompete/Bank_Marketing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd

from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import LinearSVC

In [3]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [5]:
df_train.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,6456,33,admin.,married,secondary,no,2,yes,no,unknown,20,may,201,1,-1,0,unknown,0
1,5432,35,technician,married,secondary,no,545,yes,no,cellular,16,apr,1579,1,234,4,failure,1
2,6372,39,management,married,tertiary,no,763,yes,no,cellular,11,may,877,7,300,2,other,1
3,2254,37,management,married,tertiary,no,5106,no,no,cellular,30,apr,244,1,-1,0,unknown,1
4,8350,30,unemployed,married,tertiary,no,330,no,no,cellular,14,apr,111,1,-1,0,unknown,1

In [6]:
df_train.dtypes

id           int64
age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome       str
deposit      int64
dtype: object

In [30]:
df_train.isna().sum().sum()

np.int64(0)

In [15]:
ocupatia = (df_train.groupby('job')['deposit'].mean()).idxmax()
output1 = pd.DataFrame({'subtaskID': [1], 'datapointID': [1], 'answer': ocupatia})
ocupatia

'student'

In [22]:
luna_max = df_train['month'].value_counts().idxmax()
output2 = pd.DataFrame({'subtaskID': [1], 'datapointID': [1], 'answer': luna_max})
luna_max

'may'

In [35]:
def encode_columns(df_train, df_test, columns):
    ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', dtype=int)
    encoded_train_list = ohe.fit_transform(df_train[columns])
    encoded_test_list = ohe.transform(df_test[columns])

    encoded_df_train = pd.DataFrame(encoded_train_list, columns=ohe.get_feature_names_out())
    encoded_df_test = pd.DataFrame(encoded_test_list, columns=ohe.get_feature_names_out())

    df_train[encoded_df_train.columns] = encoded_df_train
    df_test[encoded_df_test.columns] = encoded_df_test

    df_train.drop(columns, axis=1, inplace=True)
    df_test.drop(columns, axis=1, inplace=True)

def process(df_train, df_test):
    encode_list = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
    encode_columns(df_train, df_test, encode_list)
process(df_train, df_test)

C:\Users\david\AppData\Local\Temp\ipykernel_44404\2620108094.py:12: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df_train.drop(columns, axis=1, inplace=True)
C:\Users\david\AppData\Local\Temp\ipykernel_44404\2620108094.py:13: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df_test.drop(columns, axis=1, inplace=True)

In [36]:
df_train.head()

,id,age,balance,day,duration,campaign,pdays,previous,deposit,job_admin.,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,6456,33,2,20,201,1,-1,0,0,1,...,0,0,1,0,0,0,0,0,0,1
1,5432,35,545,16,1579,1,234,4,1,0,...,0,0,0,0,0,0,1,0,0,0
2,6372,39,763,11,877,7,300,2,1,0,...,0,0,1,0,0,0,0,1,0,0
3,2254,37,5106,30,244,1,-1,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,8350,30,330,14,111,1,-1,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [37]:
X = df_train.drop(['id', 'deposit'], axis=1)
y = df_train['deposit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
def evaluate_model(model):
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    print(f"Train: {f1_score(y_train, y_train_pred, average='macro')}, Test: {f1_score(y_test, y_test_pred, average='macro')}")

In [41]:
cbc = CatBoostClassifier()
cbc.fit(X_train, y_train)
evaluate_model(cbc)

Learning rate set to 0.023853
0:	learn: 0.6784878	total: 2.78ms	remaining: 2.77s
1:	learn: 0.6654414	total: 5.63ms	remaining: 2.81s
2:	learn: 0.6528672	total: 8.14ms	remaining: 2.71s
3:	learn: 0.6414828	total: 11ms	remaining: 2.73s
4:	learn: 0.6307114	total: 13.7ms	remaining: 2.72s
5:	learn: 0.6207241	total: 16.3ms	remaining: 2.69s
6:	learn: 0.6099495	total: 18.7ms	remaining: 2.65s
7:	learn: 0.5998736	total: 20.8ms	remaining: 2.58s
8:	learn: 0.5914594	total: 22.9ms	remaining: 2.52s
9:	learn: 0.5831836	total: 25ms	remaining: 2.47s
10:	learn: 0.5748743	total: 27.1ms	remaining: 2.44s
11:	learn: 0.5672494	total: 29.1ms	remaining: 2.39s
12:	learn: 0.5604520	total: 31.1ms	remaining: 2.36s
13:	learn: 0.5534803	total: 33.4ms	remaining: 2.35s
14:	learn: 0.5469728	total: 35.7ms	remaining: 2.35s
15:	learn: 0.5408253	total: 37.6ms	remaining: 2.31s
16:	learn: 0.5346706	total: 39.9ms	remaining: 2.31s
17:	learn: 0.5292562	total: 42ms	remaining: 2.29s
18:	learn: 0.5231953	total: 44.1ms	remaining: 2.28s
19:	learn: 0.5182678	total: 46.3ms	remaining: 2.27s
20:	learn: 0.5129202	total: 48.5ms	remaining: 2.26s
21:	learn: 0.5078635	total: 50.9ms	remaining: 2.26s
22:	learn: 0.5032693	total: 53.2ms	remaining: 2.26s
23:	learn: 0.4986750	total: 55.4ms	remaining: 2.25s
24:	learn: 0.4945076	total: 57.9ms	remaining: 2.26s
25:	learn: 0.4905392	total: 60ms	remaining: 2.25s
26:	learn: 0.4872383	total: 62.4ms	remaining: 2.25s
27:	learn: 0.4842567	total: 64.7ms	remaining: 2.25s
28:	learn: 0.4802163	total: 66.8ms	remaining: 2.24s
29:	learn: 0.4770670	total: 69.1ms	remaining: 2.23s
30:	learn: 0.4735573	total: 71.2ms	remaining: 2.23s
31:	learn: 0.4705090	total: 73.2ms	remaining: 2.21s
32:	learn: 0.4677320	total: 75.2ms	remaining: 2.21s
33:	learn: 0.4647355	total: 77.3ms	remaining: 2.2s
34:	learn: 0.4619570	total: 79.4ms	remaining: 2.19s
35:	learn: 0.4595114	total: 81.4ms	remaining: 2.18s
36:	learn: 0.4567855	total: 83.4ms	remaining: 2.17s
37:	learn: 0.4540335	total: 85.9ms	remaining: 2.17s
38:	learn: 0.4520047	total: 87.8ms	remaining: 2.16s
39:	learn: 0.4495533	total: 90ms	remaining: 2.16s
40:	learn: 0.4474667	total: 92.4ms	remaining: 2.16s
41:	learn: 0.4452211	total: 94.5ms	remaining: 2.16s
42:	learn: 0.4430567	total: 96.9ms	remaining: 2.15s
43:	learn: 0.4409787	total: 98.8ms	remaining: 2.15s
44:	learn: 0.4394469	total: 101ms	remaining: 2.14s
45:	learn: 0.4373507	total: 103ms	remaining: 2.13s
46:	learn: 0.4356683	total: 105ms	remaining: 2.13s
47:	learn: 0.4340231	total: 107ms	remaining: 2.12s
48:	learn: 0.4322930	total: 109ms	remaining: 2.12s
49:	learn: 0.4307612	total: 111ms	remaining: 2.11s
50:	learn: 0.4290664	total: 113ms	remaining: 2.1s
51:	learn: 0.4274783	total: 115ms	remaining: 2.1s
52:	learn: 0.4259037	total: 117ms	remaining: 2.1s
53:	learn: 0.4244783	total: 119ms	remaining: 2.09s
54:	learn: 0.4230445	total: 122ms	remaining: 2.09s
55:	learn: 0.4216535	total: 124ms	remaining: 2.08s
56:	learn: 0.4200390	total: 126ms	remaining: 2.08s
57:	learn: 0.4185607	total: 128ms	remaining: 2.07s
58:	learn: 0.4169412	total: 130ms	remaining: 2.07s
59:	learn: 0.4156271	total: 132ms	remaining: 2.07s
60:	learn: 0.4143536	total: 134ms	remaining: 2.06s
61:	learn: 0.4131716	total: 136ms	remaining: 2.06s
62:	learn: 0.4120493	total: 138ms	remaining: 2.06s
63:	learn: 0.4109753	total: 141ms	remaining: 2.06s
64:	learn: 0.4095837	total: 143ms	remaining: 2.05s
65:	learn: 0.4084356	total: 145ms	remaining: 2.05s
66:	learn: 0.4073357	total: 147ms	remaining: 2.04s
67:	learn: 0.4062410	total: 149ms	remaining: 2.04s
68:	learn: 0.4048879	total: 151ms	remaining: 2.03s
69:	learn: 0.4039594	total: 153ms	remaining: 2.03s
70:	learn: 0.4029770	total: 155ms	remaining: 2.03s
71:	learn: 0.4018120	total: 157ms	remaining: 2.02s
72:	learn: 0.4007935	total: 159ms	remaining: 2.02s
73:	learn: 0.3997752	total: 162ms	remaining: 2.02s
74:	learn: 0.3990251	total: 164ms	remaining: 2.02s
75:	learn: 0.3979666	total: 166ms	remaining: 2.01s
76:	learn: 0.3970781	total: 168ms	remaining: 2.02s
77:	learn: 0.3960026	total: 170ms	remaining: 2.01s
78:	learn: 0.3952493	total: 172ms	remaining: 2.01s
79:	learn: 0.3944796	total: 175ms	remaining: 2.01s
80:	learn: 0.3936420	total: 177ms	remaining: 2s
81:	learn: 0.3930536	total: 179ms	remaining: 2s
82:	learn: 0.3921540	total: 181ms	remaining: 2s
83:	learn: 0.3913386	total: 183ms	remaining: 2s
84:	learn: 0.3904755	total: 185ms	remaining: 2s
85:	learn: 0.3893986	total: 188ms	remaining: 1.99s
86:	learn: 0.3886719	total: 190ms	remaining: 1.99s
87:	learn: 0.3880171	total: 192ms	remaining: 1.99s
88:	learn: 0.3873389	total: 194ms	remaining: 1.99s
89:	learn: 0.3858712	total: 197ms	remaining: 1.99s
90:	learn: 0.3851881	total: 199ms	remaining: 1.99s
91:	learn: 0.3844632	total: 201ms	remaining: 1.99s
92:	learn: 0.3837787	total: 203ms	remaining: 1.98s
93:	learn: 0.3831853	total: 205ms	remaining: 1.98s
94:	learn: 0.3825141	total: 208ms	remaining: 1.98s
95:	learn: 0.3816040	total: 210ms	remaining: 1.97s
96:	learn: 0.3807958	total: 212ms	remaining: 1.97s
97:	learn: 0.3802979	total: 214ms	remaining: 1.97s
98:	learn: 0.3795780	total: 217ms	remaining: 1.97s
99:	learn: 0.3786535	total: 219ms	remaining: 1.97s
100:	learn: 0.3777538	total: 222ms	remaining: 1.97s
101:	learn: 0.3772088	total: 224ms	remaining: 1.97s
102:	learn: 0.3762616	total: 226ms	remaining: 1.97s
103:	learn: 0.3756872	total: 229ms	remaining: 1.97s
104:	learn: 0.3752168	total: 231ms	remaining: 1.97s
105:	learn: 0.3748068	total: 233ms	remaining: 1.97s
106:	learn: 0.3744379	total: 235ms	remaining: 1.96s
107:	learn: 0.3736818	total: 237ms	remaining: 1.96s
108:	learn: 0.3731278	total: 239ms	remaining: 1.96s
109:	learn: 0.3725871	total: 241ms	remaining: 1.95s
110:	learn: 0.3719956	total: 244ms	remaining: 1.95s
111:	learn: 0.3715378	total: 245ms	remaining: 1.95s
112:	learn: 0.3710138	total: 247ms	remaining: 1.94s
113:	learn: 0.3704246	total: 249ms	remaining: 1.94s
114:	learn: 0.3699318	total: 251ms	remaining: 1.93s
115:	learn: 0.3692917	total: 253ms	remaining: 1.93s
116:	learn: 0.3687267	total: 255ms	remaining: 1.93s
117:	learn: 0.3678583	total: 257ms	remaining: 1.92s
118:	learn: 0.3672648	total: 259ms	remaining: 1.92s
119:	learn: 0.3665980	total: 262ms	remaining: 1.92s
120:	learn: 0.3661418	total: 263ms	remaining: 1.91s
121:	learn: 0.3656571	total: 266ms	remaining: 1.91s
122:	learn: 0.3650321	total: 268ms	remaining: 1.91s
123:	learn: 0.3643956	total: 270ms	remaining: 1.91s
124:	learn: 0.3639618	total: 272ms	remaining: 1.9s
125:	learn: 0.3635582	total: 274ms	remaining: 1.9s
126:	learn: 0.3630872	total: 276ms	remaining: 1.9s
127:	learn: 0.3625084	total: 279ms	remaining: 1.9s
128:	learn: 0.3619798	total: 281ms	remaining: 1.9s
129:	learn: 0.3615696	total: 283ms	remaining: 1.9s
130:	learn: 0.3612055	total: 286ms	remaining: 1.89s
131:	learn: 0.3606979	total: 288ms	remaining: 1.89s
132:	learn: 0.3598365	total: 290ms	remaining: 1.89s
133:	learn: 0.3593625	total: 292ms	remaining: 1.89s
134:	learn: 0.3590131	total: 294ms	remaining: 1.89s
135:	learn: 0.3585699	total: 297ms	remaining: 1.88s
136:	learn: 0.3581144	total: 299ms	remaining: 1.88s
137:	learn: 0.3576996	total: 301ms	remaining: 1.88s
138:	learn: 0.3573612	total: 303ms	remaining: 1.88s
139:	learn: 0.3570148	total: 305ms	remaining: 1.87s
140:	learn: 0.3563360	total: 307ms	remaining: 1.87s
141:	learn: 0.3558814	total: 309ms	remaining: 1.87s
142:	learn: 0.3552526	total: 311ms	remaining: 1.86s
143:	learn: 0.3547644	total: 313ms	remaining: 1.86s
144:	learn: 0.3541703	total: 315ms	remaining: 1.86s
145:	learn: 0.3538528	total: 317ms	remaining: 1.86s
146:	learn: 0.3533045	total: 320ms	remaining: 1.86s
147:	learn: 0.3528627	total: 322ms	remaining: 1.85s
148:	learn: 0.3522850	total: 325ms	remaining: 1.85s
149:	learn: 0.3517244	total: 327ms	remaining: 1.85s
150:	learn: 0.3513759	total: 329ms	remaining: 1.85s
151:	learn: 0.3509941	total: 332ms	remaining: 1.85s
152:	learn: 0.3507820	total: 334ms	remaining: 1.85s
153:	learn: 0.3503946	total: 336ms	remaining: 1.85s
154:	learn: 0.3501100	total: 339ms	remaining: 1.84s
155:	learn: 0.3496681	total: 341ms	remaining: 1.84s
156:	learn: 0.3492560	total: 343ms	remaining: 1.84s
157:	learn: 0.3489387	total: 345ms	remaining: 1.84s
158:	learn: 0.3485847	total: 348ms	remaining: 1.84s
159:	learn: 0.3483185	total: 350ms	remaining: 1.84s
160:	learn: 0.3477823	total: 352ms	remaining: 1.84s
161:	learn: 0.3474018	total: 355ms	remaining: 1.83s
162:	learn: 0.3468558	total: 357ms	remaining: 1.83s
163:	learn: 0.3465281	total: 359ms	remaining: 1.83s
164:	learn: 0.3461748	total: 361ms	remaining: 1.83s
165:	learn: 0.3458609	total: 364ms	remaining: 1.83s
166:	learn: 0.3452686	total: 366ms	remaining: 1.82s
167:	learn: 0.3450864	total: 368ms	remaining: 1.82s
168:	learn: 0.3444311	total: 370ms	remaining: 1.82s
169:	learn: 0.3439373	total: 373ms	remaining: 1.82s
170:	learn: 0.3436595	total: 375ms	remaining: 1.82s
171:	learn: 0.3432844	total: 378ms	remaining: 1.82s
172:	learn: 0.3428629	total: 380ms	remaining: 1.82s
173:	learn: 0.3425992	total: 382ms	remaining: 1.81s
174:	learn: 0.3423535	total: 385ms	remaining: 1.81s
175:	learn: 0.3417503	total: 387ms	remaining: 1.81s
176:	learn: 0.3413103	total: 390ms	remaining: 1.81s
177:	learn: 0.3409421	total: 392ms	remaining: 1.81s
178:	learn: 0.3406373	total: 394ms	remaining: 1.81s
179:	learn: 0.3401505	total: 397ms	remaining: 1.81s
180:	learn: 0.3400029	total: 399ms	remaining: 1.81s
181:	learn: 0.3396939	total: 401ms	remaining: 1.8s
182:	learn: 0.3392462	total: 404ms	remaining: 1.8s
183:	learn: 0.3388616	total: 406ms	remaining: 1.8s
184:	learn: 0.3385959	total: 408ms	remaining: 1.8s
185:	learn: 0.3381241	total: 410ms	remaining: 1.79s
186:	learn: 0.3379122	total: 412ms	remaining: 1.79s
187:	learn: 0.3376514	total: 414ms	remaining: 1.79s
188:	learn: 0.3373136	total: 416ms	remaining: 1.79s
189:	learn: 0.3369202	total: 418ms	remaining: 1.78s
190:	learn: 0.3366788	total: 421ms	remaining: 1.78s
191:	learn: 0.3363053	total: 423ms	remaining: 1.78s
192:	learn: 0.3359214	total: 426ms	remaining: 1.78s
193:	learn: 0.3355576	total: 428ms	remaining: 1.78s
194:	learn: 0.3350204	total: 430ms	remaining: 1.77s
195:	learn: 0.3346745	total: 432ms	remaining: 1.77s
196:	learn: 0.3344219	total: 435ms	remaining: 1.77s
197:	learn: 0.3341456	total: 437ms	remaining: 1.77s
198:	learn: 0.3336924	total: 439ms	remaining: 1.77s
199:	learn: 0.3333694	total: 441ms	remaining: 1.76s
200:	learn: 0.3329715	total: 443ms	remaining: 1.76s
201:	learn: 0.3327838	total: 446ms	remaining: 1.76s
202:	learn: 0.3324822	total: 448ms	remaining: 1.76s
203:	learn: 0.3320347	total: 449ms	remaining: 1.75s
204:	learn: 0.3316871	total: 452ms	remaining: 1.75s
205:	learn: 0.3311251	total: 454ms	remaining: 1.75s
206:	learn: 0.3309396	total: 456ms	remaining: 1.75s
207:	learn: 0.3305922	total: 458ms	remaining: 1.74s
208:	learn: 0.3301071	total: 460ms	remaining: 1.74s
209:	learn: 0.3296338	total: 462ms	remaining: 1.74s
210:	learn: 0.3293547	total: 464ms	remaining: 1.73s
211:	learn: 0.3290827	total: 466ms	remaining: 1.73s
212:	learn: 0.3287183	total: 468ms	remaining: 1.73s
213:	learn: 0.3284812	total: 470ms	remaining: 1.73s
214:	learn: 0.3282686	total: 472ms	remaining: 1.72s
215:	learn: 0.3280252	total: 474ms	remaining: 1.72s
216:	learn: 0.3277639	total: 477ms	remaining: 1.72s
217:	learn: 0.3275443	total: 479ms	remaining: 1.72s
218:	learn: 0.3269297	total: 481ms	remaining: 1.72s
219:	learn: 0.3268505	total: 483ms	remaining: 1.71s
220:	learn: 0.3265636	total: 485ms	remaining: 1.71s
221:	learn: 0.3261178	total: 487ms	remaining: 1.71s
222:	learn: 0.3257084	total: 489ms	remaining: 1.7s
223:	learn: 0.3255334	total: 492ms	remaining: 1.7s
224:	learn: 0.3253965	total: 495ms	remaining: 1.7s
225:	learn: 0.3250657	total: 497ms	remaining: 1.7s
226:	learn: 0.3247257	total: 500ms	remaining: 1.7s
227:	learn: 0.3240501	total: 502ms	remaining: 1.7s
228:	learn: 0.3238775	total: 505ms	remaining: 1.7s
229:	learn: 0.3235473	total: 507ms	remaining: 1.7s
230:	learn: 0.3230986	total: 509ms	remaining: 1.69s
231:	learn: 0.3228403	total: 511ms	remaining: 1.69s
232:	learn: 0.3224973	total: 513ms	remaining: 1.69s
233:	learn: 0.3221722	total: 516ms	remaining: 1.69s
234:	learn: 0.3219437	total: 518ms	remaining: 1.69s
235:	learn: 0.3218152	total: 520ms	remaining: 1.68s
236:	learn: 0.3215782	total: 522ms	remaining: 1.68s
237:	learn: 0.3212346	total: 524ms	remaining: 1.68s
238:	learn: 0.3207042	total: 527ms	remaining: 1.68s
239:	learn: 0.3205462	total: 529ms	remaining: 1.68s
240:	learn: 0.3203545	total: 531ms	remaining: 1.67s
241:	learn: 0.3201366	total: 534ms	remaining: 1.67s
242:	learn: 0.3197001	total: 536ms	remaining: 1.67s
243:	learn: 0.3193059	total: 538ms	remaining: 1.67s
244:	learn: 0.3190443	total: 540ms	remaining: 1.66s
245:	learn: 0.3187303	total: 542ms	remaining: 1.66s
246:	learn: 0.3186042	total: 544ms	remaining: 1.66s
247:	learn: 0.3181555	total: 547ms	remaining: 1.66s
248:	learn: 0.3179749	total: 549ms	remaining: 1.66s
249:	learn: 0.3177707	total: 551ms	remaining: 1.65s
250:	learn: 0.3175886	total: 553ms	remaining: 1.65s
251:	learn: 0.3173718	total: 555ms	remaining: 1.65s
252:	learn: 0.3170347	total: 557ms	remaining: 1.65s
253:	learn: 0.3169256	total: 559ms	remaining: 1.64s
254:	learn: 0.3167943	total: 562ms	remaining: 1.64s
255:	learn: 0.3166419	total: 564ms	remaining: 1.64s
256:	learn: 0.3164754	total: 565ms	remaining: 1.63s
257:	learn: 0.3163081	total: 568ms	remaining: 1.63s
258:	learn: 0.3160328	total: 570ms	remaining: 1.63s
259:	learn: 0.3157420	total: 572ms	remaining: 1.63s
260:	learn: 0.3155431	total: 574ms	remaining: 1.63s
261:	learn: 0.3153554	total: 577ms	remaining: 1.62s
262:	learn: 0.3151942	total: 579ms	remaining: 1.62s
263:	learn: 0.3150093	total: 581ms	remaining: 1.62s
264:	learn: 0.3148137	total: 583ms	remaining: 1.62s
265:	learn: 0.3146216	total: 585ms	remaining: 1.61s
266:	learn: 0.3141556	total: 587ms	remaining: 1.61s
267:	learn: 0.3138619	total: 590ms	remaining: 1.61s
268:	learn: 0.3136023	total: 592ms	remaining: 1.61s
269:	learn: 0.3132547	total: 594ms	remaining: 1.6s
270:	learn: 0.3131101	total: 596ms	remaining: 1.6s
271:	learn: 0.3128804	total: 598ms	remaining: 1.6s
272:	learn: 0.3125653	total: 600ms	remaining: 1.6s
273:	learn: 0.3123233	total: 602ms	remaining: 1.59s
274:	learn: 0.3120746	total: 604ms	remaining: 1.59s
275:	learn: 0.3118660	total: 606ms	remaining: 1.59s
276:	learn: 0.3117463	total: 608ms	remaining: 1.59s
277:	learn: 0.3115631	total: 610ms	remaining: 1.58s
278:	learn: 0.3113142	total: 612ms	remaining: 1.58s
279:	learn: 0.3109039	total: 614ms	remaining: 1.58s
280:	learn: 0.3105697	total: 617ms	remaining: 1.58s
281:	learn: 0.3102420	total: 619ms	remaining: 1.58s
282:	learn: 0.3100827	total: 622ms	remaining: 1.57s
283:	learn: 0.3099550	total: 624ms	remaining: 1.57s
284:	learn: 0.3094092	total: 626ms	remaining: 1.57s
285:	learn: 0.3091249	total: 628ms	remaining: 1.57s
286:	learn: 0.3088274	total: 630ms	remaining: 1.57s
287:	learn: 0.3085868	total: 633ms	remaining: 1.56s
288:	learn: 0.3083006	total: 635ms	remaining: 1.56s
289:	learn: 0.3081194	total: 637ms	remaining: 1.56s
290:	learn: 0.3080045	total: 639ms	remaining: 1.56s
291:	learn: 0.3076593	total: 641ms	remaining: 1.55s
292:	learn: 0.3075207	total: 643ms	remaining: 1.55s
293:	learn: 0.3073678	total: 645ms	remaining: 1.55s
294:	learn: 0.3072434	total: 647ms	remaining: 1.55s
295:	learn: 0.3071364	total: 649ms	remaining: 1.54s
296:	learn: 0.3069754	total: 651ms	remaining: 1.54s
297:	learn: 0.3068505	total: 654ms	remaining: 1.54s
298:	learn: 0.3065983	total: 656ms	remaining: 1.54s
299:	learn: 0.3063897	total: 658ms	remaining: 1.53s
300:	learn: 0.3062656	total: 660ms	remaining: 1.53s
301:	learn: 0.3061015	total: 663ms	remaining: 1.53s
302:	learn: 0.3058981	total: 665ms	remaining: 1.53s
303:	learn: 0.3055918	total: 667ms	remaining: 1.53s
304:	learn: 0.3054905	total: 670ms	remaining: 1.53s
305:	learn: 0.3053563	total: 672ms	remaining: 1.52s
306:	learn: 0.3051391	total: 675ms	remaining: 1.52s
307:	learn: 0.3049056	total: 677ms	remaining: 1.52s
308:	learn: 0.3045082	total: 680ms	remaining: 1.52s
309:	learn: 0.3042007	total: 682ms	remaining: 1.52s
310:	learn: 0.3041173	total: 685ms	remaining: 1.52s
311:	learn: 0.3038691	total: 688ms	remaining: 1.52s
312:	learn: 0.3036683	total: 690ms	remaining: 1.51s
313:	learn: 0.3035179	total: 693ms	remaining: 1.51s
314:	learn: 0.3032197	total: 695ms	remaining: 1.51s
315:	learn: 0.3031205	total: 697ms	remaining: 1.51s
316:	learn: 0.3029955	total: 700ms	remaining: 1.51s
317:	learn: 0.3027875	total: 702ms	remaining: 1.5s
318:	learn: 0.3027012	total: 704ms	remaining: 1.5s
319:	learn: 0.3024543	total: 707ms	remaining: 1.5s
320:	learn: 0.3022337	total: 709ms	remaining: 1.5s
321:	learn: 0.3020901	total: 712ms	remaining: 1.5s
322:	learn: 0.3019278	total: 714ms	remaining: 1.5s
323:	learn: 0.3018162	total: 716ms	remaining: 1.49s
324:	learn: 0.3015978	total: 718ms	remaining: 1.49s
325:	learn: 0.3014489	total: 720ms	remaining: 1.49s
326:	learn: 0.3012547	total: 723ms	remaining: 1.49s
327:	learn: 0.3010121	total: 725ms	remaining: 1.49s
328:	learn: 0.3006012	total: 727ms	remaining: 1.48s
329:	learn: 0.3003118	total: 729ms	remaining: 1.48s
330:	learn: 0.3000564	total: 732ms	remaining: 1.48s
331:	learn: 0.2996979	total: 734ms	remaining: 1.48s
332:	learn: 0.2994473	total: 736ms	remaining: 1.47s
333:	learn: 0.2991259	total: 738ms	remaining: 1.47s
334:	learn: 0.2989842	total: 740ms	remaining: 1.47s
335:	learn: 0.2988862	total: 743ms	remaining: 1.47s
336:	learn: 0.2985142	total: 745ms	remaining: 1.46s
337:	learn: 0.2983590	total: 747ms	remaining: 1.46s
338:	learn: 0.2980395	total: 749ms	remaining: 1.46s
339:	learn: 0.2978644	total: 751ms	remaining: 1.46s
340:	learn: 0.2977360	total: 753ms	remaining: 1.46s
341:	learn: 0.2975422	total: 755ms	remaining: 1.45s
342:	learn: 0.2972774	total: 758ms	remaining: 1.45s
343:	learn: 0.2971696	total: 760ms	remaining: 1.45s
344:	learn: 0.2970073	total: 762ms	remaining: 1.45s
345:	learn: 0.2968659	total: 764ms	remaining: 1.44s
346:	learn: 0.2966288	total: 766ms	remaining: 1.44s
347:	learn: 0.2963938	total: 769ms	remaining: 1.44s
348:	learn: 0.2961796	total: 771ms	remaining: 1.44s
349:	learn: 0.2959603	total: 773ms	remaining: 1.44s
350:	learn: 0.2957952	total: 775ms	remaining: 1.43s
351:	learn: 0.2956171	total: 778ms	remaining: 1.43s
352:	learn: 0.2953458	total: 779ms	remaining: 1.43s
353:	learn: 0.2951182	total: 782ms	remaining: 1.43s
354:	learn: 0.2950165	total: 784ms	remaining: 1.42s
355:	learn: 0.2948732	total: 786ms	remaining: 1.42s
356:	learn: 0.2946432	total: 787ms	remaining: 1.42s
357:	learn: 0.2943977	total: 789ms	remaining: 1.42s
358:	learn: 0.2942775	total: 791ms	remaining: 1.41s
359:	learn: 0.2941579	total: 794ms	remaining: 1.41s
360:	learn: 0.2938918	total: 796ms	remaining: 1.41s
361:	learn: 0.2937278	total: 798ms	remaining: 1.41s
362:	learn: 0.2935915	total: 800ms	remaining: 1.4s
363:	learn: 0.2935066	total: 802ms	remaining: 1.4s
364:	learn: 0.2933226	total: 804ms	remaining: 1.4s
365:	learn: 0.2930708	total: 806ms	remaining: 1.4s
366:	learn: 0.2927848	total: 808ms	remaining: 1.39s
367:	learn: 0.2926047	total: 811ms	remaining: 1.39s
368:	learn: 0.2924612	total: 813ms	remaining: 1.39s
369:	learn: 0.2923308	total: 815ms	remaining: 1.39s
370:	learn: 0.2920079	total: 817ms	remaining: 1.39s
371:	learn: 0.2918877	total: 819ms	remaining: 1.38s
372:	learn: 0.2917171	total: 822ms	remaining: 1.38s
373:	learn: 0.2914898	total: 824ms	remaining: 1.38s
374:	learn: 0.2913747	total: 826ms	remaining: 1.38s
375:	learn: 0.2911909	total: 828ms	remaining: 1.37s
376:	learn: 0.2909988	total: 830ms	remaining: 1.37s
377:	learn: 0.2908384	total: 832ms	remaining: 1.37s
378:	learn: 0.2906506	total: 834ms	remaining: 1.37s
379:	learn: 0.2904716	total: 836ms	remaining: 1.36s
380:	learn: 0.2902274	total: 838ms	remaining: 1.36s
381:	learn: 0.2900389	total: 840ms	remaining: 1.36s
382:	learn: 0.2899208	total: 843ms	remaining: 1.36s
383:	learn: 0.2897156	total: 845ms	remaining: 1.35s
384:	learn: 0.2895381	total: 847ms	remaining: 1.35s
385:	learn: 0.2893333	total: 850ms	remaining: 1.35s

In [48]:
lr = LinearSVC()
lr.fit(X_train, y_train)
evaluate_model(lr)

Train: 0.8304115182756081, Test: 0.8193657411443926

In [49]:
lr = XGBClassifier()
lr.fit(X_train, y_train)
evaluate_model(lr)

Train: 0.9663557529401624, Test: 0.8534487393150907

In [50]:
lr = LGBMClassifier()
lr.fit(X_train, y_train)
evaluate_model(lr)

[LightGBM] [Info] Number of positive: 3411, number of negative: 3732
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001163 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1005
[LightGBM] [Info] Number of data points in the train set: 7143, number of used features: 51
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.477530 -> initscore=-0.089939
[LightGBM] [Info] Start training from score -0.089939
Train: 0.9197604430261934, Test: 0.8585433680653336

In [ ]:
def solve(model):