<a href="https://colab.research.google.com/github/comsadavid/AI-solutions/blob/main/competitions/mlcompete/Predictia_temperaturii_medii_zilnice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier

from catboost import CatBoostClassifier
from catboost import CatBoostRegressor

from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [ ]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.13/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)

In [ ]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv('test.csv')

In [ ]:
df_train.head()

   SampleID   humidity  wind_speed  ...  solar_radiation  day_of_year  temperature
0         1  52.472407   20.944851  ...       679.263245          313         5.33
1         2  87.042858   16.082891  ...       635.169456          328         3.43
2         3  73.919637    9.285828  ...       501.470266            7        -1.81
3         4  65.919509   24.413851  ...       769.233001          206        24.23
4         5  39.361118   20.541935  ...       240.332161          114        13.53

[5 rows x 9 columns]

In [ ]:
df_train.dtypes

SampleID             int64
humidity           float64
wind_speed         float64
pressure           float64
rainfall           float64
cloud_cover        float64
solar_radiation    float64
day_of_year          int64
temperature        float64
dtype: object

In [ ]:
def impute_columns(df_train, df_test, columns, strategy):
    imputer = SimpleImputer(missing_values=np.nan, strategy=strategy)
    df_train[columns] = imputer.fit_transform(df_train[columns])
    df_test[columns] = imputer.transform(df_test[columns])

In [ ]:
numeric_columns = ['humidity', 'wind_speed', 'pressure', 'rainfall', 'cloud_cover', 'solar_radiation', 'day_of_year']
impute_columns(df_train, df_test, numeric_columns, 'mean')

In [ ]:
X = df_train.drop(['SampleID', 'temperature'], axis=1)
y = df_train['temperature']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [ ]:
def evaluate_model(model):
    y_train_pred = model.predict(X_train_scaled)
    y_test_pred = model.predict(X_test_scaled)

    print(f"Train {mean_absolute_error(y_train, y_train_pred)}, Test: {mean_absolute_error(y_test, y_test_pred)}")

In [ ]:
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
evaluate_model(lr)

Train 6.117498864046102, Test: 6.497459315951824

In [ ]:
rfr = RandomForestRegressor(n_estimators=300, min_samples_split=2, min_samples_leaf=2)
rfr.fit(X_train_scaled, y_train)
evaluate_model(rfr)

Train 0.7513827175775611, Test: 1.7042331273569025

In [ ]:
cbr = CatBoostRegressor()
cbr.fit(X_train_scaled, y_train)
evaluate_model(cbr)

Learning rate set to 0.035425
0:	learn: 7.8973529	total: 3.58ms	remaining: 3.58s
1:	learn: 7.7359589	total: 7.31ms	remaining: 3.65s
2:	learn: 7.5683332	total: 11.2ms	remaining: 3.73s
3:	learn: 7.4010371	total: 14.4ms	remaining: 3.59s
4:	learn: 7.2307012	total: 17.8ms	remaining: 3.54s
5:	learn: 7.0657495	total: 21.8ms	remaining: 3.6s
6:	learn: 6.9314130	total: 25.6ms	remaining: 3.64s
7:	learn: 6.7812441	total: 29ms	remaining: 3.6s
8:	learn: 6.6346792	total: 32.5ms	remaining: 3.58s
9:	learn: 6.4945209	total: 35.7ms	remaining: 3.54s
10:	learn: 6.3544804	total: 39.3ms	remaining: 3.53s
11:	learn: 6.2233302	total: 42.6ms	remaining: 3.51s
12:	learn: 6.0962606	total: 46.1ms	remaining: 3.5s
13:	learn: 5.9811810	total: 49.9ms	remaining: 3.52s
14:	learn: 5.8492165	total: 54.4ms	remaining: 3.57s
15:	learn: 5.7366032	total: 58.2ms	remaining: 3.58s
16:	learn: 5.6188923	total: 61.8ms	remaining: 3.57s
17:	learn: 5.5115899	total: 65.1ms	remaining: 3.55s
18:	learn: 5.4004627	total: 69.3ms	remaining: 3.58s
19:	learn: 5.2907950	total: 73.4ms	remaining: 3.6s
20:	learn: 5.1821278	total: 76.8ms	remaining: 3.58s
21:	learn: 5.0804510	total: 80ms	remaining: 3.56s
22:	learn: 4.9842907	total: 84ms	remaining: 3.57s
23:	learn: 4.8782282	total: 88.2ms	remaining: 3.58s
24:	learn: 4.7928102	total: 91.9ms	remaining: 3.58s
25:	learn: 4.7132981	total: 95.2ms	remaining: 3.57s
26:	learn: 4.6293024	total: 98.5ms	remaining: 3.55s
27:	learn: 4.5489012	total: 101ms	remaining: 3.52s
28:	learn: 4.4635800	total: 105ms	remaining: 3.53s
29:	learn: 4.3637702	total: 110ms	remaining: 3.54s
30:	learn: 4.2859716	total: 116ms	remaining: 3.63s
31:	learn: 4.1932139	total: 120ms	remaining: 3.62s
32:	learn: 4.1171251	total: 123ms	remaining: 3.61s
33:	learn: 4.0443184	total: 127ms	remaining: 3.59s
34:	learn: 3.9776864	total: 129ms	remaining: 3.57s
35:	learn: 3.9040515	total: 134ms	remaining: 3.58s
36:	learn: 3.8469796	total: 137ms	remaining: 3.58s
37:	learn: 3.7868118	total: 141ms	remaining: 3.56s
38:	learn: 3.7340178	total: 144ms	remaining: 3.54s
39:	learn: 3.6696098	total: 148ms	remaining: 3.56s
40:	learn: 3.6177415	total: 153ms	remaining: 3.59s
41:	learn: 3.5643879	total: 157ms	remaining: 3.58s
42:	learn: 3.5132147	total: 160ms	remaining: 3.56s
43:	learn: 3.4620748	total: 163ms	remaining: 3.54s
44:	learn: 3.4026722	total: 166ms	remaining: 3.52s
45:	learn: 3.3491323	total: 169ms	remaining: 3.51s
46:	learn: 3.3014488	total: 172ms	remaining: 3.49s
47:	learn: 3.2472765	total: 175ms	remaining: 3.48s
48:	learn: 3.2038104	total: 179ms	remaining: 3.47s
49:	learn: 3.1523803	total: 182ms	remaining: 3.47s
50:	learn: 3.1070954	total: 188ms	remaining: 3.51s
51:	learn: 3.0598052	total: 192ms	remaining: 3.5s
52:	learn: 3.0215196	total: 196ms	remaining: 3.5s
53:	learn: 2.9771496	total: 199ms	remaining: 3.49s
54:	learn: 2.9352374	total: 202ms	remaining: 3.48s
55:	learn: 2.8942364	total: 206ms	remaining: 3.47s
56:	learn: 2.8546743	total: 209ms	remaining: 3.45s
57:	learn: 2.8185162	total: 212ms	remaining: 3.44s
58:	learn: 2.7777934	total: 215ms	remaining: 3.43s
59:	learn: 2.7404186	total: 218ms	remaining: 3.42s
60:	learn: 2.7101675	total: 223ms	remaining: 3.43s
61:	learn: 2.6693088	total: 226ms	remaining: 3.42s
62:	learn: 2.6325018	total: 229ms	remaining: 3.41s
63:	learn: 2.5944600	total: 233ms	remaining: 3.4s
64:	learn: 2.5583092	total: 238ms	remaining: 3.42s
65:	learn: 2.5287333	total: 240ms	remaining: 3.4s
66:	learn: 2.4941951	total: 243ms	remaining: 3.39s
67:	learn: 2.4704919	total: 246ms	remaining: 3.38s
68:	learn: 2.4362017	total: 249ms	remaining: 3.36s
69:	learn: 2.4118839	total: 252ms	remaining: 3.35s
70:	learn: 2.3871452	total: 256ms	remaining: 3.35s
71:	learn: 2.3610755	total: 258ms	remaining: 3.33s
72:	learn: 2.3428589	total: 262ms	remaining: 3.32s
73:	learn: 2.3179749	total: 265ms	remaining: 3.32s
74:	learn: 2.2939674	total: 268ms	remaining: 3.31s
75:	learn: 2.2714195	total: 272ms	remaining: 3.3s
76:	learn: 2.2432535	total: 275ms	remaining: 3.29s
77:	learn: 2.2137071	total: 279ms	remaining: 3.29s
78:	learn: 2.1932373	total: 282ms	remaining: 3.29s
79:	learn: 2.1688341	total: 286ms	remaining: 3.28s
80:	learn: 2.1484322	total: 289ms	remaining: 3.28s
81:	learn: 2.1283240	total: 294ms	remaining: 3.29s
82:	learn: 2.1077817	total: 299ms	remaining: 3.3s
83:	learn: 2.0873421	total: 302ms	remaining: 3.3s
84:	learn: 2.0651622	total: 306ms	remaining: 3.29s
85:	learn: 2.0422488	total: 310ms	remaining: 3.29s
86:	learn: 2.0213217	total: 313ms	remaining: 3.29s
87:	learn: 2.0031032	total: 317ms	remaining: 3.28s
88:	learn: 1.9830018	total: 320ms	remaining: 3.28s
89:	learn: 1.9631315	total: 324ms	remaining: 3.27s
90:	learn: 1.9458519	total: 327ms	remaining: 3.27s
91:	learn: 1.9294811	total: 330ms	remaining: 3.26s
92:	learn: 1.9114923	total: 334ms	remaining: 3.26s
93:	learn: 1.9007141	total: 338ms	remaining: 3.25s
94:	learn: 1.8823167	total: 341ms	remaining: 3.25s
95:	learn: 1.8656476	total: 345ms	remaining: 3.25s
96:	learn: 1.8538258	total: 349ms	remaining: 3.25s
97:	learn: 1.8396116	total: 352ms	remaining: 3.24s
98:	learn: 1.8239858	total: 356ms	remaining: 3.24s
99:	learn: 1.8082215	total: 359ms	remaining: 3.23s
100:	learn: 1.7940293	total: 363ms	remaining: 3.23s
101:	learn: 1.7826339	total: 367ms	remaining: 3.23s
102:	learn: 1.7702691	total: 370ms	remaining: 3.22s
103:	learn: 1.7595430	total: 374ms	remaining: 3.22s
104:	learn: 1.7477809	total: 378ms	remaining: 3.22s
105:	learn: 1.7381158	total: 384ms	remaining: 3.24s
106:	learn: 1.7241950	total: 391ms	remaining: 3.26s
107:	learn: 1.7152822	total: 395ms	remaining: 3.26s
108:	learn: 1.7009325	total: 400ms	remaining: 3.27s
109:	learn: 1.6917552	total: 405ms	remaining: 3.28s
110:	learn: 1.6812304	total: 409ms	remaining: 3.27s
111:	learn: 1.6700810	total: 412ms	remaining: 3.27s
112:	learn: 1.6577099	total: 415ms	remaining: 3.26s
113:	learn: 1.6454148	total: 419ms	remaining: 3.25s
114:	learn: 1.6365799	total: 423ms	remaining: 3.25s
115:	learn: 1.6249914	total: 428ms	remaining: 3.26s
116:	learn: 1.6179003	total: 431ms	remaining: 3.26s
117:	learn: 1.6089486	total: 435ms	remaining: 3.25s
118:	learn: 1.5964233	total: 439ms	remaining: 3.25s
119:	learn: 1.5896854	total: 442ms	remaining: 3.24s
120:	learn: 1.5808204	total: 446ms	remaining: 3.24s
121:	learn: 1.5712286	total: 449ms	remaining: 3.23s
122:	learn: 1.5589635	total: 453ms	remaining: 3.23s
123:	learn: 1.5503406	total: 456ms	remaining: 3.22s
124:	learn: 1.5395684	total: 460ms	remaining: 3.22s
125:	learn: 1.5287589	total: 463ms	remaining: 3.21s
126:	learn: 1.5191309	total: 466ms	remaining: 3.21s
127:	learn: 1.5080582	total: 470ms	remaining: 3.2s
128:	learn: 1.5005925	total: 474ms	remaining: 3.2s
129:	learn: 1.4942081	total: 477ms	remaining: 3.19s
130:	learn: 1.4840700	total: 481ms	remaining: 3.19s
131:	learn: 1.4775762	total: 486ms	remaining: 3.2s
132:	learn: 1.4698990	total: 492ms	remaining: 3.2s
133:	learn: 1.4620930	total: 494ms	remaining: 3.19s
134:	learn: 1.4559839	total: 497ms	remaining: 3.19s
135:	learn: 1.4479501	total: 501ms	remaining: 3.18s
136:	learn: 1.4402237	total: 504ms	remaining: 3.18s
137:	learn: 1.4344148	total: 508ms	remaining: 3.17s
138:	learn: 1.4281394	total: 511ms	remaining: 3.16s
139:	learn: 1.4182629	total: 514ms	remaining: 3.16s
140:	learn: 1.4130228	total: 519ms	remaining: 3.16s
141:	learn: 1.4034953	total: 523ms	remaining: 3.16s
142:	learn: 1.3979531	total: 526ms	remaining: 3.15s
143:	learn: 1.3901832	total: 529ms	remaining: 3.14s
144:	learn: 1.3837276	total: 532ms	remaining: 3.14s
145:	learn: 1.3778637	total: 536ms	remaining: 3.13s
146:	learn: 1.3718280	total: 539ms	remaining: 3.13s
147:	learn: 1.3668812	total: 542ms	remaining: 3.12s
148:	learn: 1.3614473	total: 546ms	remaining: 3.12s
149:	learn: 1.3555181	total: 548ms	remaining: 3.11s
150:	learn: 1.3481446	total: 552ms	remaining: 3.1s
151:	learn: 1.3430169	total: 555ms	remaining: 3.1s
152:	learn: 1.3382625	total: 558ms	remaining: 3.09s
153:	learn: 1.3307048	total: 562ms	remaining: 3.08s
154:	learn: 1.3231248	total: 565ms	remaining: 3.08s
155:	learn: 1.3163692	total: 568ms	remaining: 3.07s
156:	learn: 1.3097286	total: 573ms	remaining: 3.08s
157:	learn: 1.3049472	total: 581ms	remaining: 3.09s
158:	learn: 1.3004560	total: 584ms	remaining: 3.09s
159:	learn: 1.2944917	total: 588ms	remaining: 3.08s
160:	learn: 1.2900941	total: 593ms	remaining: 3.09s
161:	learn: 1.2845645	total: 597ms	remaining: 3.09s
162:	learn: 1.2784037	total: 600ms	remaining: 3.08s
163:	learn: 1.2743298	total: 604ms	remaining: 3.08s
164:	learn: 1.2696045	total: 606ms	remaining: 3.07s
165:	learn: 1.2655884	total: 610ms	remaining: 3.06s
166:	learn: 1.2606007	total: 613ms	remaining: 3.06s
167:	learn: 1.2550293	total: 616ms	remaining: 3.05s
168:	learn: 1.2507087	total: 619ms	remaining: 3.04s
169:	learn: 1.2472650	total: 622ms	remaining: 3.04s
170:	learn: 1.2421352	total: 626ms	remaining: 3.03s
171:	learn: 1.2378809	total: 629ms	remaining: 3.03s
172:	learn: 1.2339594	total: 632ms	remaining: 3.02s
173:	learn: 1.2274020	total: 636ms	remaining: 3.02s
174:	learn: 1.2241055	total: 639ms	remaining: 3.01s
175:	learn: 1.2190380	total: 643ms	remaining: 3.01s
176:	learn: 1.2154736	total: 647ms	remaining: 3.01s
177:	learn: 1.2121628	total: 651ms	remaining: 3s
178:	learn: 1.2076980	total: 655ms	remaining: 3s
179:	learn: 1.2037070	total: 659ms	remaining: 3s
180:	learn: 1.2002261	total: 662ms	remaining: 3s
181:	learn: 1.1959126	total: 666ms	remaining: 2.99s
182:	learn: 1.1918414	total: 670ms	remaining: 2.99s
183:	learn: 1.1876100	total: 674ms	remaining: 2.99s
184:	learn: 1.1833003	total: 678ms	remaining: 2.98s
185:	learn: 1.1789306	total: 683ms	remaining: 2.99s
186:	learn: 1.1735579	total: 687ms	remaining: 2.98s
187:	learn: 1.1694367	total: 693ms	remaining: 2.99s
188:	learn: 1.1661622	total: 696ms	remaining: 2.99s
189:	learn: 1.1619467	total: 700ms	remaining: 2.98s
190:	learn: 1.1580202	total: 704ms	remaining: 2.98s
191:	learn: 1.1551538	total: 708ms	remaining: 2.98s
192:	learn: 1.1513701	total: 711ms	remaining: 2.97s
193:	learn: 1.1476541	total: 715ms	remaining: 2.97s
194:	learn: 1.1446053	total: 719ms	remaining: 2.97s
195:	learn: 1.1413428	total: 722ms	remaining: 2.96s
196:	learn: 1.1376544	total: 725ms	remaining: 2.96s
197:	learn: 1.1320512	total: 728ms	remaining: 2.95s
198:	learn: 1.1293264	total: 732ms	remaining: 2.94s
199:	learn: 1.1258299	total: 735ms	remaining: 2.94s
200:	learn: 1.1222517	total: 740ms	remaining: 2.94s
201:	learn: 1.1178025	total: 743ms	remaining: 2.93s
202:	learn: 1.1151196	total: 746ms	remaining: 2.93s
203:	learn: 1.1126848	total: 749ms	remaining: 2.92s
204:	learn: 1.1099026	total: 753ms	remaining: 2.92s
205:	learn: 1.1061135	total: 755ms	remaining: 2.91s
206:	learn: 1.1014656	total: 758ms	remaining: 2.9s
207:	learn: 1.0976729	total: 761ms	remaining: 2.9s
208:	learn: 1.0946835	total: 765ms	remaining: 2.89s
209:	learn: 1.0914279	total: 768ms	remaining: 2.89s
210:	learn: 1.0891102	total: 772ms	remaining: 2.89s
211:	learn: 1.0851207	total: 776ms	remaining: 2.89s
212:	learn: 1.0820349	total: 782ms	remaining: 2.89s
213:	learn: 1.0791328	total: 785ms	remaining: 2.88s
214:	learn: 1.0749238	total: 789ms	remaining: 2.88s
215:	learn: 1.0711969	total: 792ms	remaining: 2.87s
216:	learn: 1.0685802	total: 795ms	remaining: 2.87s
217:	learn: 1.0652022	total: 799ms	remaining: 2.87s
218:	learn: 1.0636592	total: 803ms	remaining: 2.86s
219:	learn: 1.0607749	total: 807ms	remaining: 2.86s
220:	learn: 1.0581019	total: 810ms	remaining: 2.86s
221:	learn: 1.0544455	total: 814ms	remaining: 2.85s
222:	learn: 1.0524338	total: 818ms	remaining: 2.85s
223:	learn: 1.0493433	total: 821ms	remaining: 2.84s
224:	learn: 1.0457191	total: 824ms	remaining: 2.84s
225:	learn: 1.0421859	total: 828ms	remaining: 2.83s
226:	learn: 1.0398979	total: 831ms	remaining: 2.83s
227:	learn: 1.0379110	total: 835ms	remaining: 2.83s
228:	learn: 1.0353988	total: 838ms	remaining: 2.82s
229:	learn: 1.0316455	total: 842ms	remaining: 2.82s
230:	learn: 1.0291272	total: 845ms	remaining: 2.81s
231:	learn: 1.0274146	total: 849ms	remaining: 2.81s
232:	learn: 1.0250918	total: 852ms	remaining: 2.81s
233:	learn: 1.0217561	total: 856ms	remaining: 2.8s
234:	learn: 1.0195672	total: 860ms	remaining: 2.8s
235:	learn: 1.0174907	total: 864ms	remaining: 2.8s
236:	learn: 1.0130739	total: 867ms	remaining: 2.79s
237:	learn: 1.0115940	total: 871ms	remaining: 2.79s
238:	learn: 1.0078347	total: 875ms	remaining: 2.79s
239:	learn: 1.0050309	total: 878ms	remaining: 2.78s
240:	learn: 1.0028843	total: 881ms	remaining: 2.77s
241:	learn: 1.0006882	total: 885ms	remaining: 2.77s
242:	learn: 0.9992589	total: 888ms	remaining: 2.77s
243:	learn: 0.9957431	total: 891ms	remaining: 2.76s
244:	learn: 0.9916980	total: 896ms	remaining: 2.76s
245:	learn: 0.9897162	total: 898ms	remaining: 2.75s
246:	learn: 0.9865107	total: 903ms	remaining: 2.75s
247:	learn: 0.9832409	total: 906ms	remaining: 2.75s
248:	learn: 0.9811508	total: 910ms	remaining: 2.74s
249:	learn: 0.9797483	total: 913ms	remaining: 2.74s
250:	learn: 0.9778482	total: 917ms	remaining: 2.73s
251:	learn: 0.9769062	total: 920ms	remaining: 2.73s
252:	learn: 0.9751809	total: 923ms	remaining: 2.73s
253:	learn: 0.9723967	total: 926ms	remaining: 2.72s
254:	learn: 0.9703975	total: 930ms	remaining: 2.72s
255:	learn: 0.9687485	total: 933ms	remaining: 2.71s
256:	learn: 0.9655833	total: 936ms	remaining: 2.71s
257:	learn: 0.9640269	total: 940ms	remaining: 2.7s
258:	learn: 0.9600542	total: 943ms	remaining: 2.7s
259:	learn: 0.9585118	total: 946ms	remaining: 2.69s
260:	learn: 0.9574941	total: 949ms	remaining: 2.69s
261:	learn: 0.9548959	total: 953ms	remaining: 2.68s
262:	learn: 0.9512640	total: 956ms	remaining: 2.68s
263:	learn: 0.9496783	total: 960ms	remaining: 2.67s
264:	learn: 0.9478475	total: 963ms	remaining: 2.67s
265:	learn: 0.9452642	total: 968ms	remaining: 2.67s
266:	learn: 0.9434108	total: 972ms	remaining: 2.67s
267:	learn: 0.9405231	total: 976ms	remaining: 2.66s
268:	learn: 0.9380337	total: 979ms	remaining: 2.66s
269:	learn: 0.9348423	total: 982ms	remaining: 2.65s
270:	learn: 0.9326711	total: 985ms	remaining: 2.65s
271:	learn: 0.9323723	total: 987ms	remaining: 2.64s
272:	learn: 0.9286177	total: 990ms	remaining: 2.64s
273:	learn: 0.9249693	total: 993ms	remaining: 2.63s
274:	learn: 0.9225511	total: 997ms	remaining: 2.63s
275:	learn: 0.9189290	total: 1s	remaining: 2.62s
276:	learn: 0.9162856	total: 1s	remaining: 2.62s
277:	learn: 0.9148268	total: 1.01s	remaining: 2.61s
278:	learn: 0.9114000	total: 1.01s	remaining: 2.61s
279:	learn: 0.9103465	total: 1.01s	remaining: 2.6s
280:	learn: 0.9093869	total: 1.01s	remaining: 2.6s
281:	learn: 0.9073491	total: 1.02s	remaining: 2.59s
282:	learn: 0.9037097	total: 1.02s	remaining: 2.59s
283:	learn: 0.9009564	total: 1.02s	remaining: 2.58s
284:	learn: 0.8978429	total: 1.03s	remaining: 2.58s
285:	learn: 0.8956435	total: 1.03s	remaining: 2.58s
286:	learn: 0.8948507	total: 1.03s	remaining: 2.57s
287:	learn: 0.8939782	total: 1.04s	remaining: 2.57s
288:	learn: 0.8910893	total: 1.04s	remaining: 2.56s
289:	learn: 0.8902536	total: 1.05s	remaining: 2.56s
290:	learn: 0.8882327	total: 1.05s	remaining: 2.56s
291:	learn: 0.8857909	total: 1.05s	remaining: 2.55s
292:	learn: 0.8828906	total: 1.06s	remaining: 2.55s
293:	learn: 0.8820838	total: 1.06s	remaining: 2.55s
294:	learn: 0.8800168	total: 1.06s	remaining: 2.54s
295:	learn: 0.8776108	total: 1.07s	remaining: 2.54s
296:	learn: 0.8762932	total: 1.07s	remaining: 2.54s
297:	learn: 0.8753034	total: 1.07s	remaining: 2.53s
298:	learn: 0.8729626	total: 1.08s	remaining: 2.52s
299:	learn: 0.8706794	total: 1.08s	remaining: 2.52s
300:	learn: 0.8688349	total: 1.08s	remaining: 2.52s
301:	learn: 0.8675030	total: 1.09s	remaining: 2.52s
302:	learn: 0.8660222	total: 1.09s	remaining: 2.51s
303:	learn: 0.8633526	total: 1.09s	remaining: 2.51s
304:	learn: 0.8619514	total: 1.1s	remaining: 2.5s
305:	learn: 0.8604363	total: 1.1s	remaining: 2.5s
306:	learn: 0.8577505	total: 1.11s	remaining: 2.5s
307:	learn: 0.8546996	total: 1.11s	remaining: 2.49s
308:	learn: 0.8522582	total: 1.11s	remaining: 2.49s
309:	learn: 0.8505827	total: 1.11s	remaining: 2.48s
310:	learn: 0.8480652	total: 1.12s	remaining: 2.48s
311:	learn: 0.8470905	total: 1.12s	remaining: 2.47s
312:	learn: 0.8439796	total: 1.13s	remaining: 2.47s
313:	learn: 0.8423796	total: 1.13s	remaining: 2.46s
314:	learn: 0.8400407	total: 1.13s	remaining: 2.46s
315:	learn: 0.8365954	total: 1.13s	remaining: 2.46s
316:	learn: 0.8333205	total: 1.14s	remaining: 2.45s
317:	learn: 0.8331143	total: 1.14s	remaining: 2.44s
318:	learn: 0.8317420	total: 1.14s	remaining: 2.44s
319:	learn: 0.8287706	total: 1.15s	remaining: 2.44s
320:	learn: 0.8256153	total: 1.15s	remaining: 2.43s
321:	learn: 0.8224349	total: 1.15s	remaining: 2.43s
322:	learn: 0.8195833	total: 1.16s	remaining: 2.42s
323:	learn: 0.8185151	total: 1.16s	remaining: 2.42s
324:	learn: 0.8173259	total: 1.17s	remaining: 2.42s
325:	learn: 0.8171294	total: 1.17s	remaining: 2.41s
326:	learn: 0.8139358	total: 1.17s	remaining: 2.42s
327:	learn: 0.8120878	total: 1.18s	remaining: 2.41s
328:	learn: 0.8099804	total: 1.18s	remaining: 2.41s
329:	learn: 0.8081594	total: 1.18s	remaining: 2.4s
330:	learn: 0.8054253	total: 1.19s	remaining: 2.4s
331:	learn: 0.8045398	total: 1.19s	remaining: 2.39s
332:	learn: 0.8034082	total: 1.19s	remaining: 2.39s
333:	learn: 0.8009655	total: 1.19s	remaining: 2.38s
334:	learn: 0.8008466	total: 1.2s	remaining: 2.37s
335:	learn: 0.7999729	total: 1.2s	remaining: 2.37s
336:	learn: 0.7998581	total: 1.2s	remaining: 2.36s
337:	learn: 0.7976449	total: 1.2s	remaining: 2.35s
338:	learn: 0.7949936	total: 1.21s	remaining: 2.35s
339:	learn: 0.7942553	total: 1.21s	remaining: 2.35s
340:	learn: 0.7913492	total: 1.21s	remaining: 2.34s
341:	learn: 0.7892981	total: 1.22s	remaining: 2.34s
342:	learn: 0.7871234	total: 1.22s	remaining: 2.34s
343:	learn: 0.7849502	total: 1.22s	remaining: 2.33s
344:	learn: 0.7826931	total: 1.23s	remaining: 2.33s
345:	learn: 0.7816413	total: 1.23s	remaining: 2.32s
346:	learn: 0.7803863	total: 1.23s	remaining: 2.32s
347:	learn: 0.7780062	total: 1.23s	remaining: 2.31s
348:	learn: 0.7760738	total: 1.24s	remaining: 2.31s
349:	learn: 0.7752037	total: 1.24s	remaining: 2.3s
350:	learn: 0.7738716	total: 1.24s	remaining: 2.3s
351:	learn: 0.7722228	total: 1.25s	remaining: 2.29s
352:	learn: 0.7702677	total: 1.25s	remaining: 2.29s
353:	learn: 0.7686833	total: 1.25s	remaining: 2.28s
354:	learn: 0.7673399	total: 1.25s	remaining: 2.28s
355:	learn: 0.7655638	total: 1.26s	remaining: 2.28s
356:	learn: 0.7630569	total: 1.26s	remaining: 2.27s
357:	learn: 0.7610200	total: 1.26s	remaining: 2.27s
358:	learn: 0.7593465	total: 1.27s	remaining: 2.26s
359:	learn: 0.7563535	total: 1.27s	remaining: 2.26s
360:	learn: 0.7541194	total: 1.27s	remaining: 2.26s
361:	learn: 0.7522927	total: 1.28s	remaining: 2.25s
362:	learn: 0.7506748	total: 1.28s	remaining: 2.25s
363:	learn: 0.7488705	total: 1.28s	remaining: 2.24s
364:	learn: 0.7472414	total: 1.29s	remaining: 2.24s
365:	learn: 0.7451997	total: 1.29s	remaining: 2.24s
366:	learn: 0.7436292	total: 1.3s	remaining: 2.24s
367:	learn: 0.7410343	total: 1.3s	remaining: 2.24s
368:	learn: 0.7398554	total: 1.31s	remaining: 2.24s
369:	learn: 0.7386233	total: 1.31s	remaining: 2.24s
370:	learn: 0.7377462	total: 1.32s	remaining: 2.24s
371:	learn: 0.7363965	total: 1.32s	remaining: 2.23s
372:	learn: 0.7347394	total: 1.33s	remaining: 2.23s
373:	learn: 0.7331679	total: 1.33s	remaining: 2.23s
374:	learn: 0.7311665	total: 1.33s	remaining: 2.22s
375:	learn: 0.7291901	total: 1.34s	remaining: 2.23s
376:	learn: 0.7276280	total: 1.35s	remaining: 2.24s
377:	learn: 0.7269636	total: 1.36s	remaining: 2.24s
378:	learn: 0.7252622	total: 1.37s	remaining: 2.24s
379:	learn: 0.7235843	total: 1.37s	remaining: 2.24s
380:	learn: 0.7221011	total: 1.38s	remaining: 2.23s
381:	learn: 0.7206278	total: 1.38s	remaining: 2.23s
382:	learn: 0.7188631	total: 1.39s	remaining: 2.23s
383:	learn: 0.7175934	total: 1.39s	remaining: 2.23s
384:	learn: 0.7166283	total: 1.39s	remaining: 2.22s
385:	learn: 0.7149174	total: 1.39s	remaining: 2.22s

In [ ]:
def solve(model):
    X_pred = df_test.drop(['SampleID'], axis=1)
    # Scale X_pred using the same StandardScaler fitted on the training data
    X_pred_scaled = sc.transform(X_pred)
    y_pred = model.predict(X_pred_scaled)

    output = pd.DataFrame({
        'SampleID':df_test['SampleID'],
        'temperature': y_pred
    })

    output.to_csv("submissions2.csv", index=False)

solve(cbr)