<a href="https://colab.research.google.com/github/comsadavid/AI-solutions/blob/main/competitions/mlcompete/Robo%C8%9Bi_%C3%AEn_labirint_9_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression

from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [ ]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [ ]:
df_train

     robot_id arena_type weather  ...  speed_burst  risk_index  strategy_label
0     TR_0000      urban   clear  ...     9.821879    7.942570        explorer
1     TR_0001      urban   clear  ...     9.372641    3.101063        explorer
2     TR_0002     forest     fog  ...    14.195603   13.897243        sprinter
3     TR_0003     forest     fog  ...    13.064054    9.994055        sprinter
4     TR_0004      urban   clear  ...     9.304336    1.649628        explorer
...       ...        ...     ...  ...          ...         ...             ...
1195  TR_1195      urban   clear  ...     6.620824    4.064095        explorer
1196  TR_1196     forest   windy  ...    11.032053    2.512807        explorer
1197  TR_1197        ice   clear  ...     9.605044    6.687415        explorer
1198  TR_1198     desert   windy  ...    10.685672   10.028512       collector
1199  TR_1199     forest     fog  ...     8.656865    2.613559       collector

[1200 rows x 25 columns]

In [ ]:
df_train.dtypes

robot_id               object
arena_type             object
weather                object
difficulty              int64
laps                    int64
avg_speed_mps         float64
distance_m            float64
battery_used_pct      float64
collisions              int64
unique_cells          float64
items_collected         int64
pause_count             int64
turn_rate             float64
scan_accuracy         float64
return_time_s         float64
efficiency_score      float64
coverage_ratio        float64
scan_turn_sync        float64
pickup_efficiency     float64
detour_index          float64
safety_margin         float64
patrol_consistency    float64
speed_burst           float64
risk_index            float64
strategy_label         object
dtype: object

In [ ]:
print('Missing values per column in df_train:')
display(df_train.isnull().sum())

Missing values per column in df_train:

robot_id              0
arena_type            0
weather               0
difficulty            0
laps                  0
avg_speed_mps         0
distance_m            0
battery_used_pct      0
collisions            0
unique_cells          0
items_collected       0
pause_count           0
turn_rate             0
scan_accuracy         0
return_time_s         0
efficiency_score      0
coverage_ratio        0
scan_turn_sync        0
pickup_efficiency     0
detour_index          0
safety_margin         0
patrol_consistency    0
speed_burst           0
risk_index            0
strategy_label        0
dtype: int64

In [ ]:
print('\nTotal missing values in df_train:')
display(df_train.isnull().sum().sum())

Total missing values in df_train:

np.int64(0)

In [ ]:
df_train['avg_speed_mps'].unique().max()

np.float64(2.641200394995685)

In [ ]:
df_train['arena_type'].nunique()

4

In [ ]:
df_train['arena_type'].value_counts().idxmax()

'forest'

In [ ]:
df_train['items_collected'].unique().max()

np.int64(22)

In [ ]:
def encode_columns(columns):
    ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', dtype=int)
    encoded_train_list = ohe.fit_transform(df_train[columns])
    encoded_test_list = ohe.transform(df_test[columns])

    encoded_df_train = pd.DataFrame(encoded_train_list, columns=ohe.get_feature_names_out())
    encoded_df_test = pd.DataFrame(encoded_test_list, columns=ohe.get_feature_names_out())

    df_train[encoded_df_train.columns] = encoded_df_train
    df_test[encoded_df_test.columns] = encoded_df_test

    df_train.drop(columns, axis=1, inplace=True)
    df_test.drop(columns, axis=1, inplace=True)

def process(df_train, df_test):
    encode_list = ['arena_type', 'weather']
    encode_columns(encode_list)

In [ ]:
process(df_train, df_test)

In [ ]:
output_1 = pd.DataFrame({"robot_id": ["GLOBAL"], "subtaskID": [1], "answer": [4]})
output_2 = pd.DataFrame({"robot_id": ["GLOBAL"], "subtaskID": [2], "answer": [2.641200394995685]})
output_3 = pd.DataFrame({"robot_id": ["GLOBAL"], "subtaskID": [3], "answer": ['forest']})
output_4 = pd.DataFrame({"robot_id": ["GLOBAL"], "subtaskID": [4], "answer": [22]})

In [ ]:

X = df_train.drop(['robot_id', 'strategy_label'], axis=1)
y = df_train['strategy_label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
def evaluate_model(model):
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    print(f"Train: {f1_score(y_train, y_train_pred, average='macro')}, Test: {f1_score(y_test, y_test_pred, average='macro')}")

In [ ]:
ctb = CatBoostClassifier(verbose=False)
ctb.fit(X_train, y_train)
evaluate_model(ctb)

Train: 1.0, Test: 0.9137098021026593

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
evaluate_model(lr)

Train: 0.9708273733730328, Test: 0.9274098190932868

In [ ]:
def solve(model):
    X_pred = df_test.drop(['robot_id'], axis=1)
    y_pred = model.predict(X_pred)

    output_5 = pd.DataFrame({"robot_id": df_test['robot_id'], "subtaskID": 5, 'answer': y_pred})
    output = pd.concat([output_1, output_2, output_3, output_4, output_5], axis=0)
    output.to_csv('submission.csv', index=False)

In [ ]:
def solve(model):

    X_pred = df_test.drop(['robot_id'], axis=1)
    X_pred = sc.transform(X_pred)
    y_pred = model.predict(X_pred)

    y_pred = y_pred.flatten() # Ensures y_pred is a 1-dimensional array

    output_5 = pd.DataFrame({"robot_id": df_test['robot_id'], "subtaskID": 5, 'answer': y_pred})
    output = pd.concat([output_1, output_2, output_3, output_4, output_5], axis=0)
    output.to_csv('submission.csv', index=False)

solve(lr)